Titolo: Kiekko.tk

Anno: 2004

Descrizione: Kiekko.tk is a java-based ice hockey game, which has over 31,000 registered accounts (a majority of them are Finnish [1]). The game is developed by Jouko and Mikko Pynnönen. The game is free to play, but some features such as starting a team have to be paid for with either SMS-messages, Credit card or Phone call.



Genere: Non specificato


Valutazione: N/A
